version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /mnt/share/MEDIA/:/media 
      - /mnt/share/CloudData/Media/Music/:/media/Music
      - config:/config
    restart: unless-stopped
volumes:
  config:
