version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE, fixed "mbind: Operation not permitted"
    networks:
      - my-net
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  db_backup:
    image: raquette/docker-mysql-backup
    # Backup mode
    #command: cron_backup
    #restart: always


    command: restore
    restart: no
    networks:
      - my-net
    environment:
      BB_ACCOUNT_ID: ${BB_ACCOUNT_ID}
      BB_APPLICATION_KEY: ${BB_APPLICATION_KEY}
      MYSQL_HOST: db
      MYSQL_PASSWORD: ${ROOT_PASSWORD}
      BB_BUCKET: ${BB_BUCKET}
      BB_PATH: ${BB_PATH}
      CRONTAB: ${CRONTAB}
# Names our volume
volumes:
  my-db:
networks:
  my-net:
    driver: bridge
