version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    networks:
      - my-net
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  backup:
    image: ozzyboshi/dockermysqlbackupper
    networks:
      - my-net
    volumes:
      - '$(pwd)/rclone:/root'
    environment:
      - DBHOST= db
      - USERNAME= root
      - PASSWORD= ${ROOT_PASSWORD}
      - SECONDS=86400
      - DBNAMES=nextcloud
      - TARGETDIR=automysqlbackup/nextcloud



# Names our volume
volumes:
  my-db:
networks:
  my-net:
    driver: bridge
